### ISSUE TITLE
Wallpaper is not the live wallpaper

### ISSUE THREAD

**Issue by Sorgrum** [DerFlatulator/reddit-place-wallpaper#1]
I don't know if it's being cached or something, but the wallpaper doesnt look like it's updating. It doesnt match the one in reddit.com/r/place.

**Comment by azz** [comment]
Is your log updating? Sometimes if you click on a command prompt it actually freezes the process. Hit enter and see if it keeps going.

**Comment by Sorgrum** [comment]
The console says it's updating every 10s as it should be. I've also tried changing the wallpaper to a different image and rerunning the process. I'm on macOS by the way.

**Comment by Sorgrum** [comment]
Guess it doesn't matter anymore. I'll always have the updated version 😢
